version: '3.9'
services:
  django:
    build: .
    container_name: django
    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000
                    "
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/project
    
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
     - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  redis:
   image: redis:7
   container_name: redis
   ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery
    command: celery -A project worker -l info
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/project


  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A project beat -l info -S django
    volumes:
      - .:/project
    depends_on:
      - django
      - redis
    env_file:
      - .env

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"



volumes:
  postgres_data: 
  minio_data:

