# Generated by Django 5.0.3 on 2025-08-13 08:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminders_sent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), blank=True, default=list, size=None),
        ),
    ]
