# Generated by Django 5.0.3 on 2025-08-13 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_reminders_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['task'], name='tasks_notif_task_id_453456_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user'], name='tasks_notif_user_id_eab18b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='tasks_notif_status_9088af_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='tasks_notif_created_d51513_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'status'], name='tasks_notif_user_id_1573a4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee'], name='tasks_task_assigne_a1ddb3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='tasks_task_deadlin_736196_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='tasks_task_created_be1ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['team', 'status'], name='tasks_task_team_id_e2b702_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchangelog',
            index=models.Index(fields=['task'], name='tasks_taskc_task_id_f3d202_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchangelog',
            index=models.Index(fields=['user'], name='tasks_taskc_user_id_bdaecc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskchangelog',
            index=models.Index(fields=['created_at'], name='tasks_taskc_created_c54738_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['title'], name='tasks_team_title_c076df_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='tasks_team_is_acti_56a951_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['creator'], name='tasks_team_creator_8c0398_idx'),
        ),
    ]
